#!/usr/bin/env node

"use strict";
process.env["DEBUG"] = "airlineData*";

var program = require("commander");
var debug = require("debug")("airlineData:cli");
var chalk = require("chalk");

var airportsJs = require("./src/airports.js");
var writeJson = airportsJs.writeJson;
var airlineDestinationPagesJS = require("./src/airline_destinations_pages.js");
var getAllDestinationsPages = airlineDestinationPagesJS.getAllDestinationsPages;
var ensureDirectoryExist = airlineDestinationPagesJS.ensureDirectoryExist;
var getScraperTypeForAll = require("./src/airline_scraper.js").getScraperTypeForAll;
var getAllDestinations = require("./src/airline_destinations.js").getAllDestinations;
var getAirportsData = airportsJs.getAirportsData;
var getAllAirportsByIata = require("./src/airports_iata.js").getAllAirportsByIata;
var options = {
    "urls": "https://en.wikipedia.org/w/index.php?title=Category:Lists_of_airline_destinations",
    "destinationsFile": "./data/destination_pages.json"
  },
  airportsData;
var airlinesLinksUrl = "https://en.wikipedia.org/wiki/List_of_airline_codes";
var airlineJs = require("./src/airline.js");
var callScraper = airlineJs.callScraper;
var getAllAirlinesData = airlineJs.getAllAirlinesData;

program
  .version("0.0.1")
  .description("Retrieve airlines destinations and airports data.")
  .option("-l, --list", "List of airports with the link to the wikipedia page. (Saved to a single file)")
  .option("-d, --destinations", "Destinations of all the airlines listed on the wikipedia. (saved each airline with an individual JSON file)")
  .option("-a, --airports", "Saves the important data for each airport (saved in a single JSON file for each airport)")
  .option("-c, --companies", "Saves all the airline links and all the important information for each airline.")
  .parse(process.argv);


if (program.list) {
  // we retrieve the list of airports by IATA pages.
  // this file is going to be saved at the specified route.
  // "./data/airports_list.json"
  ensureDirectoryExist("./data/", function () {
    debug("generating list of airports by iata");
    getAllAirportsByIata("", function (err, airportsData) {
      if (err) {
        throw err;
      }
      writeJson(airportsData, "./data/airports_list.json", function () {
        debug("airports_list saved");
      });
    });
  });
}

if (program.destinations) {
  debug("Generating destination files");
  getAllDestinationsPages(options, function (err, airlines) {
    if (err) {
      throw err;
    }

    debug("Destinations File Created");

    getScraperTypeForAll({
      "airlines": airlines,
      "destinationsFile": options.destinationsFile
    }, function (err, airlineScrapers) {
      if (err) {
        throw err;
      }

      debug("scrapers finished");

      getAllDestinations(airlineScrapers, function (err) {
        if (err) {
          throw err;
        }
        debug("Routes Files Generated");
      });

    });
  });
}
if (program.airports) {
  try {
    airportsData = require("./data/airports_list.json");
    debug("Generating all airport files \n this is going to take a while...");
    getAirportsData(airportsData, function () {
      debug("Saved all the data airports");
    });
  } catch (err) {
    debug(("please generate first the list of airports."));
    debug(("Run:") + chalk.grey("'./aviation-data -l'"));

  }

}

if (program.companies) {
  callScraper(airlinesLinksUrl, "airlineLinks", function(err, airlinesLinks) {
    if (err) {throw err;}
    writeJson(airlinesLinks, "./data/airlines_links.json", function() {
      debug("airline companies links saved.");
      getAllAirlinesData(airlinesLinks, function(err) {
        if (err) {throw err;}
        debug("airlines saved.");
      });
    });
  });
}
// this is going to be the function to show the specific destinations of a specific airport.
// getAllDestinations([{
//   "name": "Air Chathams",
//   "destinationsLink": "/wiki/Air_Chathams_destinations",
//   "scraper": "table"
// }], function (err) {
//   if (err) {
//     throw err;
//   }
//   debug("files saved");
// });
